language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_script:
  - echo $CC_TEST_REPORTER_ID
  - echo $GIT_COMMIT_SHA
  - echo $GIT_BRANCH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install tox-travis
  - pip install poetry
script:
  - tox
after_script:
  - ls
  - ./cc-test-reporter after-build .coverage